apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawl4ai-mcp-server
  namespace: app-crawl4ai
  labels:
    app: crawl4ai-mcp-server
    app.kubernetes.io/name: crawl4ai
    app.kubernetes.io/instance: app-crawl4ai
    app.kubernetes.io/component: mcp-server
    app.kubernetes.io/part-of: mcp-servers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawl4ai-mcp-server
  template:
    metadata:
      labels:
        app: crawl4ai-mcp-server
        app.kubernetes.io/name: crawl4ai
        app.kubernetes.io/instance: app-crawl4ai
        app.kubernetes.io/component: mcp-server
    spec:
      containers:
        - name: crawl4ai-mcp
          image: unclecode/crawl4ai:0.7.0-r1
          ports:
            - name: mcp-server
              containerPort: 11235
              protocol: TCP
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: crawl4ai-secrets
                  key: openai-api-key
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: crawl4ai-secrets
                  key: anthropic-api-key
                  optional: true
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: crawl4ai-secrets
                  key: google-api-key
                  optional: true
            - name: PORT
              value: "11235"
            - name: HOST
              value: "0.0.0.0"
            - name: INSTALL_TYPE
              value: "default"
            - name: ENABLE_GPU
              value: "false"
          resources:
            requests:
              memory: "1Gi"
              cpu: "200m"
            limits:
              memory: "2.5Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /playground
              port: 11235
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /playground
              port: 11235
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /playground
              port: 11235
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: crawl4ai-mcp-server
                topologyKey: kubernetes.io/hostname