apiVersion: v1
kind: Service
metadata:
  name: crawl4ai-service
  namespace: app-crawl4ai
  labels:
    app: crawl4ai-mcp-server
    app.kubernetes.io/name: crawl4ai
    app.kubernetes.io/instance: app-crawl4ai
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600  # 1 hour timeout for MCP session persistence
  ports:
    - name: mcp-server
      port: 11235
      targetPort: 11235
      protocol: TCP
  selector:
    app: crawl4ai-mcp-server